# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-01 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20181117_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('A', 'ACEPTAR'), ('D', 'RECHAZAR')], default='P', max_length=3, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('Q', 'COTIZACI\xd3N'), ('F', 'FINALIZADA')], default='P', max_length=3, verbose_name='Estatus'),
        ),
    ]
