# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20181201_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'PENDIENTE'), ('Q', 'COTIZACI\xd3N'), ('S', 'SURTIDO'), ('F', 'FINALIZADA')], default='P', max_length=3, verbose_name='Estatus'),
        ),
    ]
