# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('users', '0003_auto_20180908_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=255)),
                ('signup_date', models.DateTimeField(auto_now=True)),
                ('is_reset', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='C\xf3digo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tel\xe9fono 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tel\xe9fono 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.StateMx', verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='C\xf3digo postal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Tel\xe9fono 1'),
        ),
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together=set([('token', 'email')]),
        ),
    ]
