# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180911_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=0, verbose_name='\xbfEs activo?'),
        ),
    ]
