# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-04 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, verbose_name='RFC'),
        ),
    ]
