# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181115_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono 2'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Tel\xe9fono 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tel\xe9fono 2'),
        ),
    ]
