# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityMx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_locality', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityMx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_municipality', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='StateMx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_state', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
        ),
        migrations.AddField(
            model_name='municipalitymx',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='utils.StateMx', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='localitymx',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='utils.MunicipalityMx', verbose_name='municipio'),
        ),
    ]
