# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasification',
            fields=[
                ('catalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.CatalogModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.catalogmodel',),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('catalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.CatalogModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.catalogmodel',),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseModel')),
                ('code', models.CharField(max_length=5, verbose_name='C\xf3digo')),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.basemodel',),
        ),
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseModel')),
                ('code', models.CharField(max_length=5, verbose_name='C\xf3digo')),
                ('family_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.Family', verbose_name='Familia')),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.basemodel',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.BaseModel')),
                ('code_eyamex', models.CharField(max_length=20, verbose_name='C\xf3digo EYAMEX')),
                ('code', models.CharField(max_length=15, verbose_name='C\xf3digo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('clasification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_products', to='products.Clasification', verbose_name='Clasificaci\xf3n')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_products', to='products.Color', verbose_name='Color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_products', to='products.ModelProduct', verbose_name='Modelo')),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.basemodel',),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('catalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.CatalogModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.catalogmodel',),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_products', to='products.Type', verbose_name='Tipo'),
        ),
    ]
