# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 00:28
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='product_image', verbose_name='Imagen'),
        ),
    ]
