# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasification',
            options={'verbose_name': 'Clasificaci\xf3n', 'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AlterModelOptions(
            name='modelproduct',
            options={'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
