# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180613_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
