# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20180614_0411'),
        ('products', '0004_product_meta_description'),
    ]

    operations = [
    ]
