# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_20180619_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=0, verbose_name='\xbfM\xe1s vendido?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=0, verbose_name='\xbfEs nuevo?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='spent',
            field=models.BooleanField(default=0, verbose_name='\xbfAgotado?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=products.models.get_image_path, verbose_name='Imagen'),
        ),
    ]
