# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_20180616_0150'),
        ('products', '0006_auto_20180619_0505'),
    ]

    operations = [
    ]
