# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20180619_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='description',
            field=models.TextField(default='', verbose_name='Descripci\xf3n'),
            preserve_default=False,
        ),
    ]
