# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_family_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='home_best_seller',
            field=models.BooleanField(default=False, verbose_name='\xbfM\xe1s vendido aparece en banner?'),
        ),
        migrations.AddField(
            model_name='product',
            name='home_is_new',
            field=models.BooleanField(default=False, verbose_name='\xbfEs nuevo aparece en banner?'),
        ),
    ]
